PERIODIC              
SELFGRAVITY
#RANDOMIZE_DOMAINCENTER

PMGRID=128
#TREEPM_NOTIMESPLIT
#ASMTH=0.01
MULTIPOLE_ORDER=1     
# TREE_NUM_BEFORE_NODESPLIT=6

NSOFTCLASSES=6           
NTYPES=6

POSITIONS_IN_32BIT
DOUBLEPRECISION=2

POWERSPEC_ON_OUTPUT

#    FOF
#    FOF_PRIMARY_LINK_TYPES=2
#    FOF_SECONDARY_LINK_TYPES=4
#    FOF_GROUP_MIN_LEN=32
#    FOF_LINKLENGTH=0.2
#    SUBFIND
#    SUBFIND_STORE_LOCAL_DENSITY

N_TAU=20
N_MU=20

MFLR_RST

