#!/bin/bash

#PBS -l select=1:ncpus=16:mem=5gb
#PBS -l walltime=2:00:00
#PBS -N tools_job

module purge
module load gcc gsl

cd $PBS_O_WORKDIR

./htools start
#./htools restart

# Post-processing
#source /srv/scratch/cppcnbody/py_venv/bin/activate
#./htools postprocess 
