#!/bin/bash

#PBS -l select=4:ncpus=32:mem=95gb:mpiprocs=32
#PBS -l walltime=24:00:00
#PBS -N job

# In case you want to run on infiniband nodes activate this 
##PBS -l ib=yes

cd $PBS_O_WORKDIR
source scripts/katana_modules.sh

# Change here ONLY
TYPE=start
NPROCS=32

case $TYPE in
    
    start)
    
    mpirun -np $NPROCS ./Gadget4 param.txt | tee simlog_start.txt
    
    ;;
    
    restart-mf)
    
    mpirun -np $NPROCS ./Gadget4-mf-restart param.txt | tee simlog_mf_restart.txt
    
    ;;
    
    restart-hybrid)
    
    mpirun -np $NPROCS ./Gadget4-hybrid-restart param_restart.txt | tee simlog_hybrid_restart.txt
    
    ;;

esac
