#!/bin/bash

#PBS -l select=1:ncpus=16:mem=5gb
#PBS -l walltime=2:00:00
#PBS -N out

module purge
module load gsl
module load openmpi/4.0.3


source /srv/scratch/cppcnbody/py_venv/bin/activate

export $OMP_NUM_THREADS=16
cd $PBS_O_WORKDIR

#./htools start
#./htools restart
./htools postprocess 
